"""
Document Generation API
Generates downloadable DOCX and PDF reports
"""

import io
import re
from typing import Optional
from datetime import datetime

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

router = APIRouter()


class DocumentRequest(BaseModel):
    """Request to generate a document"""
    diagnostic: str
    business_name: str
    format: str = "docx"  # docx or md


def clean_markdown_for_docx(text: str) -> str:
    """Clean markdown text for document generation"""
    # Remove excessive newlines
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text


def generate_docx(diagnostic: str, business_name: str) -> io.BytesIO:
    """Generate a DOCX document from the diagnostic"""
    try:
        from docx import Document
        from docx.shared import Inches, Pt
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="python-docx not installed. Run: pip install python-docx"
        )

    doc = Document()

    # Title
    title = doc.add_heading(f'{business_name} Market Diagnostic', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    subtitle = doc.add_paragraph(f'Generated by MarketSauce Agent')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Date
    date_para = doc.add_paragraph(f'Date: {datetime.now().strftime("%B %d, %Y")}')
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()  # Spacer

    # Process the diagnostic content
    lines = diagnostic.split('\n')
    current_list = None

    for line in lines:
        line = line.strip()
        if not line:
            current_list = None
            continue

        # Handle headers
        if line.startswith('## PHASE') or line.startswith('## '):
            doc.add_heading(line.replace('## ', '').replace('#', ''), level=1)
            current_list = None
        elif line.startswith('### '):
            doc.add_heading(line.replace('### ', ''), level=2)
            current_list = None
        elif line.startswith('#### '):
            doc.add_heading(line.replace('#### ', ''), level=3)
            current_list = None
        elif line.startswith('- ') or line.startswith('* '):
            # Bullet points
            text = line[2:]
            para = doc.add_paragraph(text, style='List Bullet')
        elif re.match(r'^\d+\.', line):
            # Numbered list
            text = re.sub(r'^\d+\.\s*', '', line)
            para = doc.add_paragraph(text, style='List Number')
        elif line.startswith('**') and line.endswith('**'):
            # Bold text as subheading
            text = line.replace('**', '')
            para = doc.add_paragraph()
            run = para.add_run(text)
            run.bold = True
        elif line.startswith('|'):
            # Table row - simplified handling
            para = doc.add_paragraph(line.replace('|', ' | '))
        else:
            # Regular paragraph
            # Handle inline bold
            if '**' in line:
                para = doc.add_paragraph()
                parts = re.split(r'\*\*', line)
                for i, part in enumerate(parts):
                    run = para.add_run(part)
                    if i % 2 == 1:
                        run.bold = True
            else:
                doc.add_paragraph(line)

    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def generate_markdown(diagnostic: str, business_name: str) -> io.BytesIO:
    """Generate a Markdown document"""
    content = f"""# {business_name} Market Diagnostic

Generated by MarketSauce Agent
Date: {datetime.now().strftime("%B %d, %Y")}

---

{diagnostic}

---

*This diagnostic was generated using the MarketSauce PRIME methodology.*
*For ongoing strategy support, use the Strategy Chat feature.*
"""
    buffer = io.BytesIO(content.encode('utf-8'))
    buffer.seek(0)
    return buffer


@router.post("/generate")
async def generate_document(request: DocumentRequest):
    """Generate a downloadable document"""
    if request.format == "docx":
        buffer = generate_docx(request.diagnostic, request.business_name)
        filename = f"{request.business_name.replace(' ', '_')}_Diagnostic.docx"
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    elif request.format == "md":
        buffer = generate_markdown(request.diagnostic, request.business_name)
        filename = f"{request.business_name.replace(' ', '_')}_Diagnostic.md"
        media_type = "text/markdown"
    else:
        raise HTTPException(status_code=400, detail="Invalid format. Use 'docx' or 'md'")

    return StreamingResponse(
        buffer,
        media_type=media_type,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"'
        }
    )


@router.post("/system-prompt")
async def generate_system_prompt_doc(
    system_prompt: str,
    business_name: str
):
    """Generate a downloadable system prompt file"""
    content = f"""# {business_name} - MarketSauce System Prompt

Use this system prompt in any AI conversation to maintain context about your market, persona, and strategy.

---

{system_prompt}

---

## How to Use This Prompt

1. Copy the entire content above
2. Start a new conversation with Claude, ChatGPT, or your preferred AI
3. Paste this as the system prompt or initial context
4. Ask questions about your market strategy, content creation, or campaign development

The AI will have full context on your buyer psychology, competitive landscape, and strategic opportunities.
"""

    buffer = io.BytesIO(content.encode('utf-8'))
    buffer.seek(0)
    filename = f"{business_name.replace(' ', '_')}_System_Prompt.md"

    return StreamingResponse(
        buffer,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"'
        }
    )
